BlogProject.UI/Controllers/CategoryController.cs
using BlogProject.CORE.Service;
using BlogProject.MODEL.Entities;
using Microsoft.AspNetCore.Mvc;

namespace BlogProject.UI.Controllers
{
    public class CategoryController : Controller
    {        
        private readonly ICoreService<Category> cs;
        //private readonly ICoreService<Post> ps;
        //private readonly ICoreService<User> us;



        public CategoryController(ICoreService<Category> _cs)
        {           
            cs = _cs;           
        }
        public IActionResult Index()
        {
            return View(cs.GetActive());
        }
    }
}

BlogProject.UI/Controllers/PostController.cs
using BlogProject.CORE.Service;
using BlogProject.MODEL.Entities;
using BlogProject.UI.Models.VM;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace BlogProject.UI.Controllers
{
    public class PostController : Controller
    {        
        private readonly ICoreService<Category> cs;
        private readonly ICoreService<Post> ps;
        private readonly ICoreService<User> us;



        public PostController(ICoreService<Category> _cs, ICoreService<Post> _ps, ICoreService<User> _us)
        {
           
            cs = _cs;
            ps = _ps;
            us = _us;
        }
        public IActionResult PostByID(Guid id)
        {
            SinglePostVM singlePost = new SinglePostVM();
            singlePost.Post = ps.GetByID(id);
            singlePost.User = us.GetbyDefault(x => x.ID == singlePost.Post.UserID);
            ViewBag.Categories = cs.GetActive();
            ViewBag.RandomPosts = ps.GetActive().Where(x => x.CategoryID == ps.GetByID(id).CategoryID).Take(3).ToList();
            return View(singlePost);
        }
        public IActionResult PostByAuthor(Guid id)
        {
            ViewBag.Author = us.GetByID(id).FirstName+" "+ us.GetByID(id).LastName;
            return View(ps.GetDefault(x=>x.UserID==id));
        }
        public IActionResult PostByCategory(Guid id)
        {
            PostUserVM postUserVM = new PostUserVM();
            postUserVM.Posts = ps.GetDefault(x=>x.CategoryID==id);
            postUserVM.Users = us.GetAll();

            return View(postUserVM);
        }
        [HttpPost]
        public IActionResult PostBySearch(string query) 
        {
            PostUserVM postUserVM = new PostUserVM();
            postUserVM.Posts = ps.GetDefault(x => x.Title.Contains(query));
            postUserVM.Users = us.GetAll();
            return View(postUserVM);
   
        }
    }
}

BlogProject.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"] - BlogProject.UI</title>
    <link rel="stylesheet" href="~/template/fontawesome/css/all.min.css"> <!-- https://fontawesome.com/ -->
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap" rel="stylesheet"> <!-- https://fonts.google.com/ -->
    <link href="~/template/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/template/css/templatemo-xtra-blog.css" rel="stylesheet">
    <!--

    TemplateMo 553 Xtra Blog

    https://templatemo.com/tm-553-xtra-blog

    -->
</head>
<body>
    <header class="tm-header" id="tm-header">
        <div class="tm-header-wrapper">
            <button class="navbar-toggler" type="button" aria-label="Toggle navigation">
                <i class="fas fa-bars"></i>
            </button>
            <div class="tm-site-header">
                <div class="mb-3 mx-auto tm-site-logo"><i class="fas fa-times fa-2x"></i></div>
                <h1 class="text-center">BuDaBi Blog</h1>
            </div>
            <nav class="tm-nav" id="tm-nav">
                <ul>
                    <li class="tm-nav-item active">
                        <a asp-controller="Home" asp-action="Index" class="tm-nav-link">
                            <i class="fas fa-home"></i>
                            Blog Home
                        </a>
                    </li>
                    <li class="tm-nav-item">
                        <a asp-controller="Category" asp-action="Index" class="tm-nav-link">
                            <i class="fas fa-pen"></i>
                            Kategoriler 
                        </a>
                       @*Kategori sayfasında kategori listelesin. Kategoriye tıklayınca kategoriler gelsin. Linkleri düzelt. Kategoriye tıklayınca da 
                           anasayfa gibi bir sayfaya gitsin.
                       *@
                    </li>
                    <li class="tm-nav-item">
                        <a href="about.html" class="tm-nav-link">
                            <i class="fas fa-users"></i>
                            Hakkında
                        </a>
                    </li>
                    <li class="tm-nav-item">
                        <a href="contact.html" class="tm-nav-link">
                            <i class="far fa-comments"></i>
                            İletişim
                        </a>
                    </li>
                </ul>
            </nav>
            <div class="tm-mb-65">
                <a rel="nofollow" href="https://fb.com/templatemo" class="tm-social-link">
                    <i class="fab fa-facebook tm-social-icon"></i>
                </a>
                <a href="https://twitter.com" class="tm-social-link">
                    <i class="fab fa-twitter tm-social-icon"></i>
                </a>
                <a href="https://instagram.com" class="tm-social-link">
                    <i class="fab fa-instagram tm-social-icon"></i>
                </a>
                <a href="https://linkedin.com" class="tm-social-link">
                    <i class="fab fa-linkedin tm-social-icon"></i>
                </a>
            </div>
            <p class="tm-mb-80 pr-5 text-white">
                Xtra Blog is a multi-purpose HTML template from TemplateMo website. Left side is a sticky menu bar. Right side content will scroll up and down.
            </p>
        </div>
    </header>
    <div class="container-fluid">
        <main class="tm-main">
            <!-- Search form -->
            <div class="row tm-row">
                <div class="col-12">
                    <form asp-controller="Post" asp-action="PostBySearch"  method="post" asp class="form-inline tm-mb-80 tm-search-form">
                        <input class="form-control tm-search-input" name="query" type="text" placeholder="Ara" aria-label="Search">
                        <button class="tm-search-button" type="submit">
                            <i class="fas fa-search tm-search-icon" aria-hidden="true"></i>
                        </button>
                    </form>
                </div>
            </div>
            <div class="row tm-row">

                @RenderBody()

            </div>
            <footer class="row tm-row">
                <hr class="col-12">
                <div class="col-md-6 col-12 tm-color-gray">
                    Design: <a rel="nofollow" target="_parent" href="https://www.bilgeadam.com/" class="tm-external-link">-BilgeAdam Teknoloji</a>
                </div>
                <div class="col-md-6 col-12 tm-color-gray tm-copyright">
                    Copyright &copy; @DateTime.Now.Year 
                </div>
            </footer>
        </main>
    </div>
    <script src="~/template/js/jquery.min.js"></script>
    <script src="~/template/js/templatemo-script.js"></script>
</body>
</html>